name: Build and push Docker image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  REPOSITORY:
  CS_PROJ_FILE: CommandsService.csproj

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Get version number
        id: version
        uses: KageKirin/get-csproj-version@v0
        with:
          file: ${{ env.CS_PROJ_FILE }}

      - name: Extract Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          tags: ${{ steps.version.outputs.version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
